In [ ]:
import numpy as np
import pandas as pd
from PIL import Image
import cv2 as cv
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.preprocessing import image
from keras.utils import img_to_array
from google.colab.patches import cv2_imshow

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
import glob
X=[]
Y=[]
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,0,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot,Blight/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,1,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,0,0,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Blight/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,1,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Blight,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,1,0,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Septoria_leaf_spot/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,1,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Septoria_leaf_spot,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,1,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___mosaic_virus/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,0,1,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___healthy/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,0,0,0,1])

In [ ]:
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32)

In [ ]:
print(X.shape)
print(Y.shape)

(3274, 256, 256, 3)
(3274, 6)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=6, test_size=0.3)
X_Val, X_test, Y_Val, Y_test = train_test_split(X_test, Y_test, random_state=6, test_size=0.5)

In [ ]:
from keras.applications.xception import Xception
base_model=Xception(input_shape=(256,256,3),include_top=False,weights='imagenet')
for layer in base_model.layers:
  layer.trainable=False

add_model = Sequential()
add_model.add(base_model)
add_model.add(Flatten())
add_model.add(Dense(1024,activation='relu'))
add_model.add(Dropout(0.3))
add_model.add(Dense(6,activation='sigmoid'))

model = add_model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

83683744/83683744 [==============================] - 1s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 xception (Functional)       (None, 8, 8, 2048)        20861480  
                                                                 
 flatten (Flatten)           (None, 131072)            0         
                                                                 
 dense (Dense)               (None, 1024)              134218752 
                                                                 
 dropout (Dropout)           (None, 1024)              0         
                                                                 
 dense_1 (Dense)             (None, 6)                 6150      
                                                                 
Total params: 155,086,382
Trainable params: 134,224,902
Non-trainable params: 20,861,480
__________________________________

In [ ]:
model.fit(X_train, Y_train, batch_size = 32, epochs = 10, verbose = 1, validation_data = (X_Val, Y_Val))

Epoch 1/10
72/72 [==============================] - 766s 11s/step - loss: 2.3317 - accuracy: 0.7145 - val_loss: 0.1800 - val_accuracy: 0.9002
Epoch 2/10
72/72 [==============================] - 755s 11s/step - loss: 0.1255 - accuracy: 0.8974 - val_loss: 0.1107 - val_accuracy: 0.9124
Epoch 3/10
72/72 [==============================] - 756s 11s/step - loss: 0.0703 - accuracy: 0.9476 - val_loss: 0.1007 - val_accuracy: 0.9226
Epoch 4/10
72/72 [==============================] - 764s 11s/step - loss: 0.0510 - accuracy: 0.9673 - val_loss: 0.1122 - val_accuracy: 0.9185
Epoch 5/10
72/72 [==============================] - 770s 11s/step - loss: 0.0388 - accuracy: 0.9668 - val_loss: 0.1259 - val_accuracy: 0.8961
Epoch 6/10
72/72 [==============================] - 775s 11s/step - loss: 0.0328 - accuracy: 0.9708 - val_loss: 0.1053 - val_accuracy: 0.9145
Epoch 7/10
72/72 [==============================] - 831s 12s/step - loss: 0.0297 - accuracy: 0.9756 - val_loss: 0.1074 - val_accuracy: 0.9145
Epoch 

In [ ]:
model.evaluate(X_test,Y_test)

16/16 [==============================] - 134s 8s/step - loss: 0.1515 - accuracy: 0.9309


[0.15146589279174805, 0.9308943152427673]

In [ ]:
Ypred=model.predict(X)
print(Ypred)

In [ ]:
model.save('/content/gdrive/MyDrive/tomato dataset_f/model_2.h5')

In [ ]:
Ypred=Ypred.round()

In [ ]:
print(Ypred)

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import multilabel_confusion_matrix

precision = precision_score(Y, Ypred,average='micro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(Y, Ypred,average='micro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(Y, Ypred,average='micro')
print('F1 score: %f' % f1)
matrix = multilabel_confusion_matrix(Y, Ypred)
print(matrix)


Precision: 0.976110
Recall: 0.958598
F1 score: 0.967275
[[[2401   29]
  [  22  822]]

 [[2427   28]
  [  16  803]]

 [[2551   13]
  [  34  676]]

 [[2977    3]
  [   2  292]]

 [[2955    7]
  [  73  239]]

 [[2625    5]
  [   3  641]]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
cr=classification_report(Y, Ypred,output_dict=False,target_names=['BacSpot', 'Blight', 'Sept','Mossaic','NutriDef','Healthy'])
print(cr)

              precision    recall  f1-score   support

     BacSpot       0.97      0.97      0.97       844
      Blight       0.97      0.98      0.97       819
        Sept       0.98      0.95      0.97       710
     Mossaic       0.99      0.99      0.99       294
    NutriDef       0.97      0.77      0.86       312
     Healthy       0.99      1.00      0.99       644

   micro avg       0.98      0.96      0.97      3623
   macro avg       0.98      0.94      0.96      3623
weighted avg       0.98      0.96      0.97      3623
 samples avg       0.97      0.97      0.97      3623



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Y_testpred=model.predict(X_test).round()


In [ ]:
# precision tp / (tp + fp)
precision = precision_score(Y_test, Y_testpred,average='micro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(Y_test, Y_testpred,average='micro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(Y_test, Y_testpred,average='micro')
print('F1 score: %f' % f1)
matrix = multilabel_confusion_matrix(Y_test, Y_testpred)
print(matrix)
cr=classification_report(Y, Ypred,output_dict=False,target_names=['BacSpot', 'Blight', 'Sept','Mossaic','NutriDef','Healthy'])
print(cr)

Precision: 0.915058
Recall: 0.858696
F1 score: 0.885981
[[[371  17]
  [ 12  92]]

 [[350  12]
  [  8 122]]

 [[388   6]
  [ 14  84]]

 [[436   2]
  [  0  54]]

 [[434   3]
  [ 42  13]]

 [[377   4]
  [  2 109]]]
              precision    recall  f1-score   support

     BacSpot       0.97      0.97      0.97       844
      Blight       0.97      0.98      0.97       819
        Sept       0.98      0.95      0.97       710
     Mossaic       0.99      0.99      0.99       294
    NutriDef       0.97      0.77      0.86       312
     Healthy       0.99      1.00      0.99       644

   micro avg       0.98      0.96      0.97      3623
   macro avg       0.98      0.94      0.96      3623
weighted avg       0.98      0.96      0.97      3623
 samples avg       0.97      0.97      0.97      3623



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
