In [ ]:
import numpy as np
import pandas as pd
from PIL import Image
import cv2 as cv
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.preprocessing import image
from keras.utils import img_to_array
from google.colab.patches import cv2_imshow

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
import glob
X=[]
Y=[]
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,0,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot,Blight/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,1,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Bacterial_spot,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([1,0,0,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Blight/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,1,0,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Blight,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,1,0,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Septoria_leaf_spot/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,1,0,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___Septoria_leaf_spot,nutrition_def/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,1,0,1,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___mosaic_virus/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,0,1,0,0])

In [ ]:
path='/content/gdrive/MyDrive/tomato dataset_f/Tomato___healthy/*.*'
for file_i in glob.glob(path):
  img=cv.imread(file_i)
  img=cv.resize(img,(256,256))
  img = img_to_array(img)
  img = img/255
  X.append(img)
  Y.append([0,0,0,0,0,1])

In [ ]:
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32)

In [ ]:
print(X.shape)
print(Y.shape)

(3274, 256, 256, 3)
(3274, 6)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=6, test_size=0.3)
X_Val, X_test, Y_Val, Y_test = train_test_split(X_test, Y_test, random_state=6, test_size=0.5)

In [ ]:
from keras.applications.inception_v3 import InceptionV3
base_model=InceptionV3(input_shape=(256,256,3),include_top=False,weights='imagenet')
for layer in base_model.layers:
  layer.trainable=False

add_model = Sequential()
add_model.add(base_model)
add_model.add(Flatten())
add_model.add(Dense(1024,activation='relu'))
add_model.add(Dropout(0.3))
add_model.add(Dense(6,activation='sigmoid'))

model = add_model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

87910968/87910968 [==============================] - 1s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inception_v3 (Functional)   (None, 6, 6, 2048)        21802784  
                                                                 
 flatten (Flatten)           (None, 73728)             0         
                                                                 
 dense (Dense)               (None, 1024)              75498496  
                                                                 
 dropout (Dropout)           (None, 1024)              0         
                                                                 
 dense_1 (Dense)             (None, 6)                 6150      
                                                                 
Total params: 97,307,430
Trainable params: 75,504,646
Non-trainable params: 21,802,784
____________________________________

In [ ]:
model.fit(X_train, Y_train, batch_size = 32, epochs = 10, verbose = 1, validation_data = (X_Val, Y_Val))

Epoch 1/10
72/72 [==============================] - 456s 6s/step - loss: 3.3990 - accuracy: 0.6430 - val_loss: 0.2076 - val_accuracy: 0.8269
Epoch 2/10
72/72 [==============================] - 456s 6s/step - loss: 0.1599 - accuracy: 0.8621 - val_loss: 0.1783 - val_accuracy: 0.8289
Epoch 3/10
72/72 [==============================] - 451s 6s/step - loss: 0.0914 - accuracy: 0.9289 - val_loss: 0.1645 - val_accuracy: 0.8758
Epoch 4/10
72/72 [==============================] - 452s 6s/step - loss: 0.0686 - accuracy: 0.9424 - val_loss: 0.1400 - val_accuracy: 0.8737
Epoch 5/10
72/72 [==============================] - 447s 6s/step - loss: 0.0432 - accuracy: 0.9616 - val_loss: 0.1334 - val_accuracy: 0.8961
Epoch 6/10
72/72 [==============================] - 447s 6s/step - loss: 0.0395 - accuracy: 0.9564 - val_loss: 0.1252 - val_accuracy: 0.8880
Epoch 7/10
72/72 [==============================] - 446s 6s/step - loss: 0.0284 - accuracy: 0.9633 - val_loss: 0.1442 - val_accuracy: 0.8921
Epoch 8/10
72

In [ ]:
model.evaluate(X_test,Y_test)

16/16 [==============================] - 75s 5s/step - loss: 0.2066 - accuracy: 0.8862


[0.206618994474411, 0.8861788511276245]

In [ ]:
Ypred=model.predict(X)
print(Ypred)

103/103 [==============================] - 510s 5s/step
[[9.9938786e-01 1.3919969e-03 1.6522875e-04 9.1581576e-08 3.0261115e-05
  9.1164489e-09]
 [9.9456346e-01 9.7346591e-04 1.3390701e-02 8.0049290e-07 1.2722980e-03
  1.5383303e-07]
 [9.8333430e-01 1.1918255e-02 1.5550210e-04 5.3459962e-06 5.4143305e-04
  4.3205883e-09]
 ...
 [9.1599276e-07 1.6633279e-05 2.2516566e-05 1.8687231e-08 5.7264326e-05
  1.0000000e+00]
 [1.4655242e-06 6.0598075e-04 1.5341693e-03 6.6582859e-04 8.8873255e-04
  9.9866611e-01]
 [8.4914492e-10 1.8788466e-03 8.1304791e-10 6.3632872e-09 5.9428394e-06
  9.9999648e-01]]


In [ ]:
model.save('/content/gdrive/MyDrive/tomato dataset_f/model_1.h5')

In [ ]:
Ypred=Ypred.round()

In [ ]:
print(Ypred)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import multilabel_confusion_matrix

precision = precision_score(Y, Ypred,average='micro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(Y, Ypred,average='micro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(Y, Ypred,average='micro')
print('F1 score: %f' % f1)
matrix = multilabel_confusion_matrix(Y, Ypred)
print(matrix)


Precision: 0.966544
Recall: 0.940933
F1 score: 0.953566
[[[2409   21]
  [  39  805]]

 [[2403   52]
  [  27  792]]

 [[2546   18]
  [  55  655]]

 [[2977    3]
  [  19  275]]

 [[2950   12]
  [  72  240]]

 [[2618   12]
  [   2  642]]]


In [ ]:
cr=classification_report(Y, Ypred,output_dict=False,target_names=['BacSpot', 'Blight', 'Sept','Mossaic','NutriDef','Healthy'])
print(cr)

              precision    recall  f1-score   support

     BacSpot       0.97      0.95      0.96       844
      Blight       0.94      0.97      0.95       819
        Sept       0.97      0.92      0.95       710
     Mossaic       0.99      0.94      0.96       294
    NutriDef       0.95      0.77      0.85       312
     Healthy       0.98      1.00      0.99       644

   micro avg       0.97      0.94      0.95      3623
   macro avg       0.97      0.92      0.94      3623
weighted avg       0.97      0.94      0.95      3623
 samples avg       0.95      0.95      0.95      3623



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Y_testpred=model.predict(X_test).round()


16/16 [==============================] - 77s 5s/step


In [ ]:
# precision tp / (tp + fp)
precision = precision_score(Y_test, Y_testpred,average='micro')
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(Y_test, Y_testpred,average='micro')
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(Y_test, Y_testpred,average='micro')
print('F1 score: %f' % f1)
matrix = multilabel_confusion_matrix(Y_test, Y_testpred)
print(matrix)
cr=classification_report(Y_test, Y_testpred,output_dict=False,target_names=['BacSpot', 'Blight', 'Sept','Mossaic','NutriDef','Healthy'])
print(cr)

Precision: 0.875000
Recall: 0.798913
F1 score: 0.835227
[[[377  11]
  [ 20  84]]

 [[331  31]
  [ 12 118]]

 [[383  11]
  [ 25  73]]

 [[437   1]
  [ 10  44]]

 [[433   4]
  [ 42  13]]

 [[376   5]
  [  2 109]]]
              precision    recall  f1-score   support

     BacSpot       0.97      0.95      0.96       844
      Blight       0.94      0.97      0.95       819
        Sept       0.97      0.92      0.95       710
     Mossaic       0.99      0.94      0.96       294
    NutriDef       0.95      0.77      0.85       312
     Healthy       0.98      1.00      0.99       644

   micro avg       0.97      0.94      0.95      3623
   macro avg       0.97      0.92      0.94      3623
weighted avg       0.97      0.94      0.95      3623
 samples avg       0.95      0.95      0.95      3623



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
